import Link from "next/link";

/**
 * DESIGN-DIRECTION.md §2: dogwatch's one diagram is the gate flow — propose
 * -> gate opened -> decide (three channels) -> execute exactly once, with
 * the 48h timeout into REFUSED as the single amber edge. Generated by
 * scripts/diagram.mjs, CI drift-checked (pnpm diagram:check) exactly like
 * the brand assets, so this image cannot silently outpace its source.
 *
 * A plain <img> (SPEC §10 D3: no route handler, no image optimizer) with a
 * full descriptive `alt` — the SVG itself also carries a real <title>/
 * <desc> (BRAND-KIT: "not aria-label='image'"), but that only reaches
 * assistive tech when the SVG is embedded inline; referenced via <img> the
 * `alt` text is what a screen reader announces, so it repeats the same
 * description rather than falling back to an empty or generic one.
 */
export function GateFlowSection() {
  return (
    <section className="flex flex-col gap-4 border-t border-rule pt-8">
      <div className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold text-ink">Every action outside this repo waits behind a gate</h2>
        <p className="max-w-prose text-sm text-ink">
          A confirmed finding proposes an action. Opening the gate starts a 48-hour timer. A human
          decides through one of three channels. Approval executes the action exactly once. Rejection
          refuses it — and so does silence: 48 hours with no decision refuses it too. That timeout path
          is the only edge in this diagram that fires without a human, which is why it is the one amber
          line.
        </p>
      </div>
      {/* The diagram is dense — small text on a 1140-wide canvas — so it
       * shrinks to illegible below ~700px if forced to fit the viewport.
       * Instead of shrinking it, the diagram keeps a readable minimum width
       * and this wrapper scrolls horizontally; the page body itself never
       * scrolls sideways. Readable at 320px means "you can still read every
       * word", not "the whole image fits on a phone screen at once". */}
      <div className="w-full overflow-x-auto border border-rule">
        <img
          src="/diagram/gate-flow.svg"
          width={1140}
          height={460}
          alt="Flow diagram of the dogwatch gate: a confirmed finding is proposed as an action. Opening the gate starts a 48-hour timer and notifies through an issue in dogwatch's own repo plus an optional webhook. A human decides through one of three channels — a single-use HMAC token on the web, a GitHub Actions workflow_dispatch usable from the mobile app with no token, or the CLI as a recorded break-glass — all converging on one decision. Approval executes the action exactly once through sluice's idempotent effect runner. Rejection refuses it. So does 48 hours passing with no decision at all — that timeout path, drawn in amber, is the only edge that fires without a human choosing anything."
          className="block w-full min-w-[700px]"
        />
      </div>
      <p className="text-sm text-ink-muted">
        <Link href="/docs#gate-flow" className="text-ink underline decoration-rule underline-offset-2 hover:decoration-ink">
          Read the gate flow field by field, and the three decision channels →
        </Link>
      </p>
    </section>
  );
}
