// Generates fixtures/violations/*.json — SPEC §11.2: "one record per rubric
// rule (15+): ... each must fail with its exact code; a violation that
// merely warns fails CI." Every fixture starts from ONE real, honest record
// (built through the actual pipeline — replay probe, frozen clock, seeded
// random, SPEC §11) and is then mutated to break exactly one rule, with
// `chain.recordHash` recomputed afterward so R12 (record tampering) stays
// clean everywhere except its own fixture — the whole point of a "planted"
// violation is that it is isolated, not a pile of coincidental breakage.
//
// Run: `pnpm exec tsx scripts/gen-fixtures.mts`. Committed output, not
// regenerated by CI (unlike schemas/run-record.v1.json) — a rubric fixture
// is content a human authored on purpose, not a mechanical projection of
// another file.
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { canonicalStringify } from "../packages/dogwatch/src/record/canonical.js";
import { computeRecordHash } from "../packages/dogwatch/src/record/hash.js";
import { buildRun } from "../packages/dogwatch/src/record/build-run.js";
import { createReplayHttpProbe } from "../packages/dogwatch/src/probe/replay.js";
import type { Check, RunRecord } from "../packages/dogwatch/src/record/schema.js";
import type { TargetsFile } from "../packages/dogwatch/src/record/targets-schema.js";

const OUT_DIR = fileURLToPath(new URL("../fixtures/violations", import.meta.url));
const FIXED_NOW_MS = Date.parse("2026-08-08T15:00:00.000Z");

const TARGETS: TargetsFile = {
  formatVersion: 1,
  sites: [
    {
      id: "agentjames",
      name: "Agent James",
      url: "https://agentjames.vercel.app",
      repo: "jamessuuu/agentjames",
      deployed: true,
      families: ["reach"],
      expectedHeaders: [],
      weightBudgetBytes: 300_000,
    },
  ],
  repos: [],
  packages: [],
  artifacts: [],
  actionPolicy: { issueRepos: ["jamessuuu/dogwatch"], confirmations: 2, gateTimeoutHours: 48 },
};

/** One real record, honestly built: a 503 response gives one `finding`
 * check (status) and one `pass` check (redirect chain — status-independent,
 * and this is the first-ever observation so there is no baseline to drift
 * from) — enough structure for every rule below to have something to break. */
async function baseRecord(): Promise<RunRecord> {
  return buildRun({
    targets: TARGETS,
    targetsHash: "fixture-targets-hash",
    probe: createReplayHttpProbe({
      get: {
        "https://agentjames.vercel.app": {
          status: 503,
          finalUrl: "https://agentjames.vercel.app",
          redirects: [],
          headers: {},
          bodyText: "<html></html>",
          bodyTruncated: false,
          bytes: 13,
          ms: 88,
          bodySha256: "0".repeat(64),
        },
      },
    }),
    now: () => FIXED_NOW_MS,
    random: () => 0.5,
    commit: "f".repeat(40),
    watchVersion: "0.1.0-alpha.0",
    checkPackVersion: "1",
    pricingManifest: "pricing.2026-08-08.json",
    kind: "manual",
    scheduledFor: null,
    trigger: { workflow: null, runUrl: null, actor: "fixture-generator" },
    prevRecord: null,
  });
}

function findCheck(record: RunRecord, verdict: Check["verdict"]): Check {
  const check = record.checks.find((c) => c.verdict === verdict);
  if (check === undefined) throw new Error(`fixture setup: no ${verdict} check in the base record`);
  return check;
}

/** Recompute chain.recordHash after mutating a record — every fixture
 * except r12 must stay internally consistent (R12 is what's targeting the
 * hash itself; every other fixture failing R12 by ACCIDENT would defeat the
 * "one planted record per rule" isolation SPEC §11.2 asks for). */
function rehash(record: RunRecord): RunRecord {
  return { ...record, chain: { ...record.chain, recordHash: computeRecordHash(record) } };
}

type Mutator = (base: RunRecord) => RunRecord;

const MUTATIONS: { file: string; code: string; mutate: Mutator }[] = [
  {
    file: "r01-no-checks",
    code: "E_NO_CHECKS",
    mutate: (base) =>
      rehash({
        ...base,
        checks: [],
        findings: [],
        absenceOfEvidence: { statement: "no checks ran this watch", checksClean: 0, byFamily: {}, notChecked: [] },
      }),
  },
  {
    file: "r01b-check-nonterminal",
    code: "E_CHECK_NONTERMINAL",
    mutate: (base) => {
      const passCheck = findCheck(base, "pass");
      const checks = base.checks.map((c) => (c.id === passCheck.id ? { ...c, verdict: "pending" as const } : c));
      return rehash({ ...base, checks });
    },
  },
  {
    file: "r02-orphan-finding",
    code: "E_ORPHAN_FINDING",
    mutate: (base) => {
      const passCheck = findCheck(base, "pass");
      const findings = base.findings.map((f) => ({ ...f, checkId: passCheck.id }));
      return rehash({ ...base, findings });
    },
  },
  {
    file: "r03-unreported-check",
    code: "E_UNREPORTED_CHECK",
    mutate: (base) => rehash({ ...base, findings: [] }),
  },
  {
    file: "r04-unsourced-finding",
    code: "E_UNSOURCED_FINDING",
    // `sources.length === 0` is a Zod-level constraint (`.min(1)`) — a
    // record like that never parses as a RunRecord at all, so it can't
    // reach the rubric to be planted here. R4's rubric-reachable half is
    // the OTHER two conditions SPEC §7 names: retrievedAt inside
    // [startedAt, endedAt], and evidencePath resolving inside the record —
    // this fixture breaks the timestamp bound.
    mutate: (base) => {
      const findings = base.findings.map((f) => ({
        ...f,
        sources: f.sources.map((s) => ({ ...s, retrievedAt: "2020-01-01T00:00:00.000Z" })),
      }));
      return rehash({ ...base, findings });
    },
  },
  {
    file: "r05-no-absence-section",
    code: "E_NO_ABSENCE_SECTION",
    mutate: (base) => {
      const findingCheck = findCheck(base, "finding");
      const checks = base.checks.map((c) => (c.id === findingCheck.id ? { ...c, verdict: "pass" as const } : c));
      // Both checks now pass (2), but checksClean is deliberately left at
      // the stale pre-mutation value (1) — the exact "did not update the
      // absence section" mistake R5 exists to catch.
      return rehash({
        ...base,
        checks,
        findings: [],
        absenceOfEvidence: { ...base.absenceOfEvidence, checksClean: 1 },
      });
    },
  },
  {
    file: "r06-silent-skip",
    code: "E_SILENT_SKIP",
    mutate: (base) => {
      const passCheck = findCheck(base, "pass");
      const checks = base.checks.map((c) =>
        c.id === passCheck.id ? { ...c, verdict: "skipped" as const, skipReason: "no_baseline" as const } : c
      );
      // absenceOfEvidence.notChecked is deliberately NOT updated with the
      // new skip — R6's exact failure mode.
      return rehash({ ...base, checks, absenceOfEvidence: { ...base.absenceOfEvidence, checksClean: 0 } });
    },
  },
  {
    file: "r07-action-unbacked",
    code: "E_ACTION_UNBACKED",
    mutate: (base) =>
      rehash({
        ...base,
        actions: [{ id: "act-1", kind: "issue.open", target: "jamessuuu/dogwatch", status: "executed" }],
      }),
  },
  {
    file: "r08-gate-unbacked",
    code: "E_GATE_UNBACKED",
    mutate: (base) =>
      rehash({
        ...base,
        gates: [
          {
            id: "gate-1",
            key: "fingerprint-1",
            status: "pending",
            openedAt: base.startedAt,
            expiresAt: "2099-01-01T00:00:00.000Z",
          },
        ],
      }),
  },
  {
    file: "r09-cost-unbacked",
    code: "E_COST_UNBACKED",
    mutate: (base) =>
      rehash({ ...base, cost: { ...base.cost, microUsd: 999, breakdown: { probe: 5 } } }),
  },
  {
    file: "r10-advisory-ungrounded",
    code: "E_ADVISORY_UNGROUNDED",
    mutate: (base) => {
      const findings = base.findings.map((f) => ({
        ...f,
        advisory: { severity: "high" as const, note: "advisory text", model: "claude-haiku-4-5", agreesWithRule: true },
      }));
      // llm.calls stays 0 (honest: M0-M2 makes no model call) — an advisory
      // present without a call behind it is exactly R10's target.
      return rehash({ ...base, findings });
    },
  },
  {
    file: "r11-chain-broken",
    code: "E_CHAIN_BROKEN",
    mutate: (base) => {
      const events = base.audit.events.map((e, i) => (i === base.audit.events.length - 1 ? { ...e, hash: "0".repeat(64) } : e));
      // audit.verified is left at its original `true` — stale relative to
      // the now-corrupted chain, which is what R11 catches.
      return rehash({ ...base, audit: { ...base.audit, events } });
    },
  },
  {
    file: "r12-record-tampered",
    code: "E_RECORD_TAMPERED",
    // Deliberately NOT rehashed — chain.recordHash is left pointing at the
    // pre-tamper content while a visible field changes underneath it.
    mutate: (base) => ({ ...base, commit: "0".repeat(40) }),
  },
  {
    file: "r13-manufactured-finding",
    code: "E_MANUFACTURED_FINDING",
    mutate: (base) => {
      const findings = base.findings.map((f) => ({ ...f, statement: "this text was hand-edited, not template-derived" }));
      return rehash({ ...base, findings });
    },
  },
  {
    file: "r14-metric-as-finding",
    code: "E_METRIC_AS_FINDING",
    mutate: (base) =>
      rehash({
        ...base,
        metrics: [
          {
            id: "metric:agentjames:reach.ms",
            targetId: "agentjames",
            name: "response_time_ms",
            value: 88,
            unit: "ms",
            note: "recorded, not judged",
            // `Metric` is a `z.looseObject` (schema.ts) — a stray extra key
            // like `severity` is structurally legal TS, which is exactly
            // why R14 has to be a runtime rubric check instead of a type.
            severity: "high",
          },
        ],
      }),
  },
  {
    file: "r15-secret-leak",
    code: "E_SECRET_LEAK",
    mutate: (base) =>
      rehash({ ...base, trigger: { ...base.trigger, actor: "ghp_abcdefghijklmnopqrstuvwxyz012345" } }),
  },
];

async function main() {
  const base = await baseRecord();
  mkdirSync(OUT_DIR, { recursive: true });
  for (const { file, code, mutate } of MUTATIONS) {
    const record = mutate(base);
    writeFileSync(`${OUT_DIR}/${file}.json`, canonicalStringify(record), "utf8");
    console.log(`wrote fixtures/violations/${file}.json (${code})`);
  }
}

await main();
