/** `runs/index.json` (SPEC §4 module map). Regenerated by `dogwatch render`
 * and drift-checked in CI (SPEC §11.5). */
import { z } from "zod";
import { RunKindSchema } from "./schema.js";

export const RunIndexEntrySchema = z.strictObject({
  runId: z.string().min(1),
  path: z.string().min(1),
  kind: RunKindSchema,
  startedAt: z.iso.datetime(),
  endedAt: z.iso.datetime(),
  checksTotal: z.number().int().nonnegative(),
  passes: z.number().int().nonnegative(),
  findings: z.number().int().nonnegative(),
  skips: z.number().int().nonnegative(),
  errors: z.number().int().nonnegative(),
  gatesOpened: z.number().int().nonnegative(),
  costMicroUsd: z.number().int().nonnegative(),
  quiet: z.boolean(),
  recordHash: z.string().min(1),
});
export type RunIndexEntry = z.infer<typeof RunIndexEntrySchema>;

export const RunIndexFileSchema = z.strictObject({
  formatVersion: z.literal(1),
  // Chronological, oldest first — the latest published run is always the
  // last element (SPEC Decision 1: git history is the time series).
  runs: z.array(RunIndexEntrySchema),
});
export type RunIndexFile = z.infer<typeof RunIndexFileSchema>;
